import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt 
df=pd.read_csv("Cleaned IBM HR.csv")
#1)What is the age distribution of all employees? (Histogram)
plt.figure(figsize=(8,5))
sns.histplot(df["Age"],bins=20,kde=True,color="steelblue")
plt.title("Age Distribution of Employee")
plt.xlabel("Age")
plt.ylabel("Number of Employees")
plt.show()
# 2)What is the monthly income distribution? (Histogram/KDE)
plt.figure(figsize=(8,5))
sns.histplot(df["Monthly_Income"],color="PURPLE",bins=20,kde=True)
plt.title("Income Distribution of Employee")
plt.xlabel("Income")
plt.ylabel("Number of Employees")
plt.show()
#3)	What is the overall attrition split (Yes vs No)? (Count plot / Pie chart)
#plt.figure(figsize=(8,5))
df["Attrition"].value_counts().plot(kind="pie",autopct="%1.1f%%",colors=("green","red"),explode=(0,0.1))
plt.title("Attrition Split")
plt.legend()
plt.show()
#4)What is the distribution of years at company? (Histogram)
plt.figure(figsize=(8,5))
sns.histplot(df["Years_At_Company"],kde=True,bins=15,color="Orange")
plt.title("Tenure Distribution")
plt.xlabel("Tenure")
plt.ylabel("Number of Employees")
plt.show()
# 5)How does attrition differ by department in %? (Bar chart)
att_by_dept=df.groupby("Department")["Attrition_binary"].mean()*100
plt.figure(figsize=(8,5))
plt.title("Attrition by Department")
att_by_dept.plot(kind="bar",color="red")
plt.ylabel("Attrition Rate(%)")
plt.xticks(rotation=0)
plt.show()
# 5)How does attrition differ by department? (count plot)(Yes/No)
sns.countplot(data=df,x="Department",hue="Attrition",palette={"No":"red","Yes":"green"})
plt.title("Attrition by Department")
plt.ylabel("Count of Employee")
plt.show()
# 6)How does attrition differ by job role? (Bar chart)
plt.figure(figsize=(11,6))
att_by_job=df.groupby("Job_Role")["Attrition_binary"].mean()*100
att_by_job=att_by_job.sort_values(ascending=False)
sns.barplot(att_by_job,color="red")
plt.title("Attrition Rate by Role")
plt.xlabel("Job Role")
plt.ylabel("Attrition Rate(%)")
plt.xticks(fontsize=7,rotation=0)
plt.tight_layout()
plt.show()
#7)How does attrition differ by gender? (Count plot)
plt.figure(figsize=(6,5))
sns.countplot(data=df, x="Gender", hue="Attrition", palette={"No":"green","Yes":"red"})
plt.title("Attrition by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Employees")
plt.show()
# 8)How does attrition differ by overtime status? (count plot)
plt.figure(figsize=(8,5))
sns.countplot(data=df,x="Over_Time",hue="Attrition",palette={"No":"green","Yes":"red"})
plt.title("Attrition by Overtime Status")
plt.xlabel("Overtime")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.show()
#9)How does attrition differ by marital status? (Count plot)
plt.figure(figsize=(8,5))
sns.countplot(data=df,x="Marital_Status",hue="Attrition",palette={"Yes":"red","No":"green"})
plt.title("Attrition by Marital Status")
plt.xlabel("Marital Status")
plt.ylabel("Employee Count")
plt.tight_layout()
plt.show()
# 10)How does age distribution differ between employees who left vs stayed?
plt.figure(figsize=(8,5))
sns.histplot(data=df, x="Age", hue="Attrition", kde=True, palette={"No":"green","Yes":"red"})
plt.tight_layout()
plt.title("Age Distribution: Employees Who Left vs Stayed")
plt.xlabel("Age")
plt.ylabel("Attrition")
plt.show()
#same using boxplot
sns.boxplot(data=df,x="Attrition",y="Age")
plt.show()
sns.kdeplot(data=df,x="Age",hue="Attrition")
plt.show()
# 11)How does monthly income differ between employees who left vs stayed? (Box plot)
plt.figure(figsize=(8,5))
sns.boxplot(data=df,x="Attrition",y="Monthly_Income",palette={"Yes":"green","No":"red"})
plt.tight_layout()
plt.title("Salary Distribution: Employees Who Left vs Stayed")
plt.xlabel("Attrition")
plt.ylabel("Monthly Income")
plt.show()
# 12)How does job satisfaction level relate to attrition? (Bar chart or violin plot)
att_rate_per_jsl=df.groupby("Job_Satisfaction")["Attrition_binary"].mean()*100
plt.figure(figsize=(8,5))
sns.barplot(att_rate_per_jsl,color="red")
plt.title("Attrition Rate by Job Satisfaction Level")
plt.xlabel("Job Satisfaction Level")
plt.ylabel("Attrition Rate (%)")
plt.show()
#13)How does work-life balance relate to attrition? (Bar chart)
att_by_wlf=df.groupby("Work_Life_Balance")["Attrition_binary"].mean()*100
plt.figure(figsize=(8,5))
sns.barplot(att_by_wlf,color="red")
plt.title("Attrition Rate by Work-Life Balance")
plt.xlabel("Work-Life Balance")
plt.ylabel("Attrition Rate (%)")
plt.show()
# 14)How does distance from home relate to attrition? (Box plot)
plt.figure(figsize=(8,5))
sns.boxplot(data=df,y="Distance_From_Home",x="Attrition",palette={"Yes":"red","No":"green"})
plt.title("Distance From Home by Attrition")
plt.xlabel("Attrition")
plt.ylabel("Distance From Home (km)")
plt.show()
#15)How does monthly income vary by job level? (Box plot)
plt.figure(figsize=(8,5))
sns.boxplot(data=df,x="Job_Level",y="Monthly_Income",color="teal")
plt.title("Monthly Income By Job Level")
plt.xlabel("Job Level")
plt.ylabel("Monthly Income ")
plt.show()
#16)How does monthly income vary by department? (Box plot)
plt.figure(figsize=(8,5))
sns.boxplot(data=df,y="Monthly_Income",x="Department",color="skyblue")
plt.xlabel("Department")
plt.title("Monthly Income Distribution by Department")
plt.ylabel("Monthly Income in")
plt.tight_layout()
plt.show()
# 17)How does monthly income vary by education field? (Box plot)
plt.figure(figsize=(8,5))
sns.boxplot(data=df,y="Monthly_Income",x="Education_Field",color="skyblue")
plt.xlabel("Education Field")
plt.xticks(fontsize="8")
plt.title("Monthly Income Distribution by Education field")
plt.ylabel("Monthly Income ")
plt.show()
# 18)What is the correlation between all numeric variables? (Heatmap)
plt.figure(figsize=(8,5))
corr2=df[["Age","Daily_Rate","Attrition_binary","Education","Monthly_Income","Job_Level","Work_Life_Balance"]]# Lots of numeric columns Heatmap become complex thus selected the few columns
sns.heatmap(corr2.corr(),annot=True,cmap="coolwarm",fmt=".2f")
plt.title("Correlation Heatmap - Key HR Metrics")
plt.show()
