CREATE DATABASE HR_IBM;
USE HR_IBM;
SELECT * FROM IBM_DATASET ;
-- 1)OVERALL ATTRITION RATE
SELECT ROUND(AVG(ATTRITION_BINARY)*100,2) AS "ATTRITION RATE" FROM IBM_DATASET;
-- 2.What is the total employee count by attrition status (Yes/No)?
SELECT ATTRITION,COUNT(*) AS COUNT FROM IBM_DATASET GROUP BY ATTRITION;
-- 3.What is the average monthly income overall?
SELECT ROUND(AVG(MONTHLY_INCOME),2) AS "AVERAGE INCOME(MONTHLY)" FROM IBM_DATASET;
-- 4)What is the attrition rate by department?
SELECT DEPARTMENT,ROUND(AVG(ATTRITION_BINARY)*100,2) AS "AVERAGE ATTRITION RATE" FROM IBM_DATASET GROUP BY DEPARTMENT ORDER BY AVG(ATTRITION_BINARY) DESC;
-- 5)What is the attrition rate by job role?
SELECT JOB_ROLE,ROUND(AVG(ATTRITION_BINARY)*100,2) AS "ATTRITION RATE" FROM IBM_DATASET GROUP BY JOB_ROLE ORDER BY AVG(ATTRITION_BINARY) DESC;
-- 6)Which departments have an attrition rate above the company average?
SELECT DEPARTMENT,ROUND(AVG(ATTRITION_BINARY)*100,2) AS "ATTRITION RATE" FROM IBM_DATASET GROUP BY DEPARTMENT HAVING AVG(ATTRITION_BINARY)*100 > (SELECT AVG(ATTRITION_BINARY)*100 FROM IBM_DATASET);
-- 7)What is the average income by department and gender?
SELECT DEPARTMENT,GENDER,ROUND(AVG(MONTHLY_INCOME),2) AS "AVERAGE INCOME(MONTHLY" FROM IBM_DATASET GROUP BY DEPARTMENT,GENDER ORDER BY DEPARTMENT,AVG(MONTHLY_INCOME) DESC;
-- 8)What is the attrition rate by tenure group?
SELECT TENURE_GROUP AS "TENURE GROUP",ROUND(AVG(ATTRITION_BINARY)*100,2) AS "ATTRITION RATE" FROM IBM_DATASET GROUP BY TENURE_GROUP ORDER BY AVG(ATTRITION_BINARY) DESC;
-- 9)What is the attrition rate by income band?
SELECT INCOME_BAND,ROUND(AVG(ATTRITION_BINARY)*100,2) AS "ATTRITION RATE" FROM IBM_DATASET GROUP BY INCOME_BAND ORDER BY AVG(ATTRITION_BINARY) DESC;
-- 10)What is the attrition rate for employees who work overtime vs. those who don't?
SELECT OVER_TIME AS "OVER TIME",ROUND(AVG(ATTRITION_BINARY)*100,2) AS "ATTRITION RATE" FROM IBM_DATASET GROUP BY OVER_TIME ORDER BY AVG(ATTRITION_BINARY)*100 DESC;
-- 11)How does attrition rate vary by job satisfaction level (Low/Medium/High/Very High)?
SELECT CASE WHEN JOB_SATISFACTION =1 THEN "LOW"
WHEN JOB_SATISFACTION =2 THEN "MEDIUM"
WHEN JOB_SATISFACTION =3 THEN "HIGH"
ELSE "VERY HIGH" END AS "SATISFACTION LEVEL",ROUND(AVG(ATTRITION_BINARY)*100,2) AS "ATTRITION RATE" FROM IBM_DATASET GROUP BY JOB_SATISFACTION ORDER BY AVG(ATTRITION_BINARY)*100 DESC; 
-- 12)Which employees can be flagged as "high risk" based on low satisfaction + overtime + low tenure?
SELECT EMPLOYEE_NUMBER,DEPARTMENT, JOB_ROLE, CASE WHEN JOB_SATISFACTION<=2 AND OVER_TIME="YES" AND YEARS_AT_COMPANY<=2 THEN "HIGH RISK"
ELSE "NORMAL" END AS EMPLOYEE_RISK FROM IBM_DATASET;
-- 13)Which employees earn above their department's average income?
SELECT EMPLOYEE_NUMBER,DEPARTMENT,MONTHLY_INCOME FROM IBM_DATASET I WHERE MONTHLY_INCOME>(SELECT AVG(MONTHLY_INCOME) 
FROM IBM_DATASET WHERE DEPARTMENT=I.DEPARTMENT);
-- 14)Which department has the single highest attrition rate?
SELECT DEPARTMENT,ROUND(AVG(ATTRITION_BINARY)*100,2) AS ATTRITION_RATE FROM IBM_DATASET GROUP BY DEPARTMENT ORDER BY ATTRITION_RATE DESC LIMIT 1;
-- 15)Which employees have tenure below the average tenure of employees who left?
SELECT EMPLOYEE_NUMBER,DEPARTMENT,YEARS_AT_COMPANY FROM IBM_DATASET WHERE YEARS_AT_COMPANY< (SELECT AVG(YEARS_AT_COMPANY) FROM IBM_DATASET WHERE ATTRITION="YES");
-- 16)Which departments have below-average tenure compared to the company average? (CTE)
WITH CTE1 AS(SELECT DEPARTMENT,AVG(YEARS_AT_COMPANY)AS AVG_TENURE FROM IBM_DATASET GROUP BY DEPARTMENT)
SELECT * FROM CTE1 WHERE  AVG_TENURE <(SELECT AVG(YEARS_AT_COMPANY) FROM IBM_DATASET);
-- 17)Which departments have an attrition rate above 15%? (CTE)
WITH CTE2 AS (SELECT DEPARTMENT,ROUND(AVG(ATTRITION_BINARY)*100,2) AS ATTRITION_RATE FROM IBM_DATASET GROUP BY DEPARTMENT)
SELECT *FROM CTE2 WHERE ATTRITION_RATE>15;
SELECT DEPARTMENT,ROUND(AVG(ATTRITION_BINARY)*100,2) AS ATTRITION_RATE FROM IBM_DATASET GROUP BY DEPARTMENT HAVING ATTRITION_RATE>15;
-- Solved two ways to compare CTE vs HAVING approach
-- 18)How do departments rank by attrition rate? (RANK)
SELECT DEPARTMENT,ROUND(AVG(ATTRITION_BINARY)*100,2) AS ATTRITION_RATE,RANK() OVER(ORDER BY AVG(ATTRITION_BINARY)*100 DESC) AS "RANK" FROM IBM_DATASET GROUP BY DEPARTMENT;
-- 19)How do employees rank by income within their department? (RANK/PARTITION BY)
SELECT EMPLOYEE_NUMBER,DEPARTMENT,MONTHLY_INCOME,RANK() OVER(PARTITION BY DEPARTMENT ORDER BY MONTHLY_INCOME DESC) AS "RANK" FROM IBM_DATASET;
-- 20)What is the running total of employees who left, ordered by years at company? (window SUM)
SELECT Employee_Number, Years_At_Company, Attrition_Binary,SUM(Attrition_Binary) OVER (ORDER BY Years_At_Company) AS Running_Attrition_Count
FROM ibm_dataset WHERE Attrition_Binary = 1 ORDER BY Years_At_Company;
-- 21)How does each employee's income compare to their department's average? (window AVG, no subquery)
SELECT EMPLOYEE_NUMBER,DEPARTMENT,MONTHLY_INCOME,AVG(MONTHLY_INCOME) OVER(PARTITION BY DEPARTMENT) FROM IBM_DATASET ORDER BY MONTHLY_INCOME DESC;
-- 22)Who are the top 3 highest-paid employees in each department? (ROW_NUMBER)
SELECT * FROM (SELECT Employee_Number, Department, Job_Role, Monthly_Income,ROW_NUMBER() OVER (PARTITION BY Department ORDER BY Monthly_Income DESC) AS rn
FROM IBM_DATASET) ranked WHERE rn <= 3;